name: "Build Android app"

on:
  workflow_dispatch:
    branches: [main]
    # can add push and pull_request here

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run npm Install
        run: |
             npm i -g corepack
             npm install

      - name: Grant permission to Gradlew
        run: chmod +x ./android/gradlew

      - name: Set Gradle options for memory
        run: echo "org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8" >> ./android/gradle.properties  # Set Gradle memory options

      - name: Build application
        env:
          GRADLE_OPTS: "-Xmx4096m"
        run: |
             cd ./android
             ./gradlew assembleDebug

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3
